<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.isuziki</groupId>
        <artifactId>isuzuki</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>isuzuki-examples</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isuziki</groupId>
            <artifactId>isuzuki-utils</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isuziki</groupId>
            <artifactId>isuzuki-oss-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isuziki</groupId>
            <artifactId>isuzuki-oss-s3</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isuziki</groupId>
            <artifactId>isuzuki-oss-aliyun</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isuziki</groupId>
            <artifactId>isuzuki-microservices-traces</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isuziki</groupId>
            <artifactId>isuzuki-microservices-metrics</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isuziki</groupId>
            <artifactId>isuzuki-microservices-logs</artifactId>
        </dependency>
        <dependency>
            <groupId>com.isuziki</groupId>
            <artifactId>isuzuki-http-apilog</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>