spring.application.name=isuzuki-example

logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]\\t

management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=30s

# management.tracing.sampling.probability=1.0

management.opentelemetry.tracing.limits.max-attributes=64
management.opentelemetry.tracing.limits.max-attribute-value-length=256
management.opentelemetry.tracing.export.otlp.endpoint=https://localhost:4318/v1/traces

management.opentelemetry.logging.limits.max-attributes=64
management.opentelemetry.logging.limits.max-attribute-value-length=256
management.opentelemetry.logging.export.schedule-delay=15s
management.opentelemetry.logging.export.otlp.endpoint=https://localhost:4318/v1/logs

management.opentelemetry.resource-attributes.service.name=my-spring-boot-app
management.opentelemetry.resource-attributes.service.version=1.0.0
management.opentelemetry.resource-attributes.deployment.environment=dev
management.opentelemetry.resource-attributes.service.namespace=dev

info.app.name=isuzuki-example
info.app.version=1.0.0
info.app.description=Demo for Spring Boot 4.1.1 Observability

isuzuki.http.apilog.enabled=true