isuzuki.oss.s3.enabled=true
isuzuki.oss.s3.provider=s3
isuzuki.oss.s3.buckets[0].access-key=xxx
isuzuki.oss.s3.buckets[0].secret-key=yyy
isuzuki.oss.s3.buckets[0].endpoint=http://localhost:9000
isuzuki.oss.s3.buckets[0].bucket-name=pri
isuzuki.oss.s3.buckets[0].custom-endpoint=http://oss.net
isuzuki.oss.s3.buckets[0].enable-presigned=true
isuzuki.oss.s3.buckets[1].access-key=xx
isuzuki.oss.s3.buckets[1].secret-key=yy
isuzuki.oss.s3.buckets[1].endpoint=http://localhost:9000
isuzuki.oss.s3.buckets[1].bucket-name=pub
isuzuki.oss.s3.buckets[1].custom-endpoint=http://oss.net
isuzuki.oss.s3.buckets[1].enable-presigned=false

isuzuki.fs.app.default.pub-path=66696c65
isuzuki.fs.app.default.pri-path=file
isuzuki.fs.app.default.max-size=20MB

isuzuki.fs.app.1915166938.pub-path=6169
isuzuki.fs.app.1915166938.pri-path=ai
isuzuki.fs.app.1915166938.max-size=20MB

